"""Per-resource-type category and colour: the report's Service dots and legend,
the graph's node colours, and GET /api/service-meta. Split out of template.py."""

from ...aws_services import service_of


# Category and colour per service, for the report and graph. Categories are AWS's own
# (pinned to tools/aws_service_coverage.csv by a test), with four deliberate overrides.
SERVICE_META = {
    "EC2Instance":                {"color": "#ED7100", "category": "Compute"},
    "ReservedInstance":           {"color": "#ED7100", "category": "Compute"},
    "SpotInstanceRequest":        {"color": "#ED7100", "category": "Compute"},
    "LaunchTemplate":             {"color": "#ED7100", "category": "Compute"},
    "AMI":                        {"color": "#ED7100", "category": "Compute"},
    "LambdaFunction":             {"color": "#ED7100", "category": "Compute"},
    "ElasticBeanstalkEnvironment": {"color": "#ED7100", "category": "Compute"},
    "ElasticBeanstalkApplication": {"color": "#ED7100", "category": "Compute"},
    "EBSVolume":                  {"color": "#7AA116", "category": "Storage"},
    "EBSSnapshot":                {"color": "#7AA116", "category": "Storage"},
    "BackupVault":                {"color": "#7AA116", "category": "Storage"},
    "BackupPlan":                 {"color": "#7AA116", "category": "Storage"},
    "SageMakerEndpoint":          {"color": "#009D7F", "category": "Machine Learning"},
    "SageMakerNotebook":          {"color": "#009D7F", "category": "Machine Learning"},
    "SageMakerStudioApp":         {"color": "#009D7F", "category": "Machine Learning"},
    "SageMakerTrainingJob":       {"color": "#009D7F", "category": "Machine Learning"},
    "S3Bucket":                   {"color": "#7AA116", "category": "Storage"},
    "EFSFileSystem":              {"color": "#7AA116", "category": "Storage"},
    "RDSInstance":                {"color": "#527FFF", "category": "Databases"},
    "RDSCluster":                 {"color": "#527FFF", "category": "Databases"},
    "DocumentDBCluster":          {"color": "#527FFF", "category": "Databases"},
    "DocumentDBInstance":         {"color": "#527FFF", "category": "Databases"},
    "NeptuneCluster":             {"color": "#527FFF", "category": "Databases"},
    "NeptuneInstance":            {"color": "#527FFF", "category": "Databases"},
    "RDSSnapshot":                {"color": "#527FFF", "category": "Databases"},
    "DynamoDBTable":              {"color": "#527FFF", "category": "Databases"},
    "ElastiCacheCluster":         {"color": "#527FFF", "category": "Databases"},
    "OpenSearchDomain":           {"color": "#0F7B8A", "category": "Analytics"},
    "OpenSearchServerlessCollection": {"color": "#0F7B8A", "category": "Analytics"},
    "RedshiftCluster":            {"color": "#527FFF", "category": "Databases"},
    "RedshiftServerlessWorkgroup": {"color": "#527FFF", "category": "Databases"},
    "LoadBalancer":               {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    # AWS files these three under EC2/Compute; see the note above on why they
    # stay here.
    "SecurityGroup":              {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "NetworkInterface":           {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "VPC":                        {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "Subnet":                     {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "RouteTable":                 {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "InternetGateway":            {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "NatGateway":                 {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "VpcEndpoint":                {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "TransitGateway":             {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "VPNConnection":              {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "ElasticIP":                  {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "AmplifyApp":                 {"color": "#C925D1", "category": "Front-End Web & Mobile"},
    "APIGatewayRestApi":          {"color": "#C925D1", "category": "Front-End Web & Mobile"},
    "APIGatewayV2Api":            {"color": "#C925D1", "category": "Front-End Web & Mobile"},
    "APIGatewayDomainName":       {"color": "#C925D1", "category": "Front-End Web & Mobile"},
    "AppSyncApi":                 {"color": "#C925D1", "category": "Front-End Web & Mobile"},
    "SQSQueue":                   {"color": "#01A88D", "category": "Application Integration"},
    "KinesisStream":              {"color": "#0F7B8A", "category": "Analytics"},
    "FirehoseStream":             {"color": "#0F7B8A", "category": "Analytics"},
    "MSKCluster":                 {"color": "#0F7B8A", "category": "Analytics"},
    "GlueJob":                    {"color": "#0F7B8A", "category": "Analytics"},
    "GlueCrawler":                {"color": "#0F7B8A", "category": "Analytics"},
    "SNSTopic":                   {"color": "#01A88D", "category": "Application Integration"},
    "EventBridgeRule":            {"color": "#01A88D", "category": "Application Integration"},
    "EventBridgeSchedule":        {"color": "#01A88D", "category": "Application Integration"},
    "EventBridgeBus":             {"color": "#01A88D", "category": "Application Integration"},
    # KeyPair likewise: AWS files it under EC2/Compute, but an SSH key is a
    # credential and belongs beside the other credentials.
    "KeyPair":                    {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "IAMRole":                    {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "IAMUser":                    {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "IAMGroup":                   {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "IAMPolicy":                  {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "IAMRoleUnusedAccessFinding": {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "CognitoUserPool":            {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "KMSKey":                     {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "Secret":                     {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "ACMCertificate":             {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "WAFWebACL":                  {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "NetworkFirewall":            {"color": "#DD344C", "category": "Security, Identity, & Compliance"},
    "Route53HostedZone":          {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "Route53ResolverEndpoint":    {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "CloudFrontDistribution":     {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "ECRRepository":              {"color": "#B35C00", "category": "Containers"},
    "AutoScalingGroup":           {"color": "#ED7100", "category": "Compute"},
    "TargetGroup":                {"color": "#8C4FFF", "category": "Networking & Content Delivery"},
    "StepFunctionsStateMachine":  {"color": "#01A88D", "category": "Application Integration"},
    "ECSCluster":                 {"color": "#B35C00", "category": "Containers"},
    "ECSService":                 {"color": "#B35C00", "category": "Containers"},
    "EKSCluster":                 {"color": "#B35C00", "category": "Containers"},
    "CodeBuildProject":           {"color": "#2E4A7D", "category": "Developer Tools"},
    "CodePipeline":               {"color": "#2E4A7D", "category": "Developer Tools"},
    "CloudFormationStack":        {"color": "#E7157B", "category": "Management & Governance"},
    "SSMParameter":               {"color": "#E7157B", "category": "Management & Governance"},
    "CloudWatchAlarm":            {"color": "#E7157B", "category": "Management & Governance"},
    "CloudWatchLogGroup":         {"color": "#E7157B", "category": "Management & Governance"},
    "CloudTrailTrail":            {"color": "#E7157B", "category": "Management & Governance"},
    "XRayGroup":                  {"color": "#2E4A7D", "category": "Developer Tools"},
    "XRaySamplingRule":           {"color": "#2E4A7D", "category": "Developer Tools"},
}

# The AWS service each type is filed under (EC2, S3...), for both front ends'
# Service filter. Derived from aws_services.py so the two tables cannot drift.
for _resource_type, _meta in SERVICE_META.items():
    _meta["service"] = service_of(_resource_type)[1]
