"""Regenerate present/graph/aws_icons_data.py from the Iconify logos set (CC0):
python3 tools/build_aws_icons.py path/to/@iconify-json/logos/icons.json"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
OUT = os.path.join(ROOT, "aws_resource_audit", "present", "graph", "aws_icons_data.py")


def wanted():
    # Read the names without importing icons.py, which imports the file this writes.
    namespace = {}
    source = open(os.path.join(os.path.dirname(OUT), "icons.py")).read()
    table = source[source.index("SERVICE_ICONS = {"):source.index("\n\ndef icon_for")]
    exec(table, namespace)
    return sorted(set(namespace["SERVICE_ICONS"].values()) | set(namespace["EXTRA_ICONS"]))


def main(path):
    logos = json.load(open(path))
    icons = {}
    for name in wanted():
        source = "aws" if name == "aws" else f"aws-{name}"
        icon = logos["icons"][source]
        icons[name] = {k: icon[k] for k in ("body", "width", "height", "left", "top") if k in icon}
    lines = ['"""GENERATED by tools/build_aws_icons.py - do not edit.',
             "",
             'AWS service icons from the Iconify "logos" set by Gil Barbara, CC0-1.0.',
             '"""',
             "",
             "ICON_PACK = {",
             '    "prefix": "aws",',
             f'    "width": {logos.get("width", 256)},',
             f'    "height": {logos.get("height", 256)},',
             '    "icons": {']
    for name, icon in icons.items():
        lines.append(f"        {name!r}: {json.dumps(icon)},")
    lines += ["    },", "}", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {len(icons)} icons to {OUT}")


if __name__ == "__main__":
    main(sys.argv[1])
